In [69]:
print('Hello world')



Hello world


In [70]:
#1. Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.19.2


In [71]:
#2. How to create a 1D array?
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
#3. How to create a boolean array?
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [73]:
#4. How to extract items that satisfy a given condition from 1D array?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [74]:
#5. How to replace items that satisfy a condition with another value in numpy array?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [75]:
#6. How to replace items that satisfy a condition without affecting the original array?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.arange(10)
new = np.where(arr % 2 == 1, -1, arr)
print(arr)
new

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [76]:
#7. How to reshape an array?
np.arange(10)
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
#8. How to stack two arrays vertically?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [78]:
#9. How to stack two arrays horizontally?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [79]:
#10. How to generate custom sequences in numpy without hardcoding?
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [80]:
#11. How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [81]:
#12. How to remove from one array those items that exist in another?
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [83]:
#13. How to get the positions where elements of two arrays match?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int32),)

In [90]:
#14. How to extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [101]:
#15. How to make a python function that handles scalars to work on numpy arrays?
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [107]:
#16. How to swap two columns in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
arr
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [116]:
#17. How to swap two rows in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [131]:
#18. How to reverse the rows of a 2D array?
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [141]:
#19. How to reverse the columns of a 2D array?
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [173]:
#20. How to create a 2D array containing random floats between 5 and 10?
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

[[7.25093107 6.82263273 8.63772333]
 [6.81523185 9.97544003 8.42103982]
 [8.41782781 7.65957091 7.66969209]
 [7.45595057 5.34571693 8.91519181]
 [7.71637734 7.4884667  5.35501375]]


In [193]:
#21. How to print only 3 decimal places in python numpy array?
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.571, 0.067, 0.749],
       [0.712, 0.048, 0.466],
       [0.924, 0.298, 0.626],
       [0.652, 0.452, 0.352]])

In [221]:
#22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
np.set_printoptions(suppress=False)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

[[5.434049e-04 2.783694e-04 4.245176e-04]
 [8.447761e-04 4.718856e-06 1.215691e-04]
 [6.707491e-04 8.258528e-04 1.367066e-04]]


array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [231]:
#23. How to limit the number of items printed in output of numpy array?
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [248]:
#24. How to print the full numpy array without truncating
import sys
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)
np.set_printoptions(threshold=sys.maxsize)
a

[ 0  1  2 ... 12 13 14]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [264]:
#25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [315]:
#Do the following exercise in a Jupyter Notebook (a GitHub Link would be the best):
import pandas as pd
url = 'https://raw.githubusercontent.com/edlich/eternalrepo/master/DS-WAHLFACH/countries.csv'
df = pd.read_csv (url,error_bad_lines=False)

row_count, column_count = df.shape
print('Basic informations')
print("Number of rows ", row_count)
print("Number of columns ", column_count)
print('')
print('---------------------------------------')
print('Show the last 4 rows of the data frame.')
df1 = df.iloc[1:]
print(df1)
print('')
print('---------------------------------------')
print('Show all the row of countries who have the EURO.')
df2 = df.loc[df['Currency'] == 'EUR']
print(df2)
print('')
print('---------------------------------------')
print('Show only name and Currency in a new data frame.')
df3 = df[['Name', 'Currency']]
print(df3)
print('')
print('---------------------------------------')
print('Show only the rows/countries that have more than 2000 BIP (it is in Milliarden USD Bruttoinlandsprodukt)')
df4 = df.loc[df['BIP'] > 2000]
print(df4)
print('')
print('---------------------------------------')
print('Select all countries where with inhabitants between 50 and 150 Mio')
df5 = df.loc[(df['People'] >= 50000000) & (df['People'] <= 150000000)]
print(df5)
print('')
print('---------------------------------------')
print('Change BIP to Bip')
df6 = df.rename({'BIP' : 'Bip'}, axis=1)
print(df6)
print('')
print('---------------------------------------')
print('Calculate the Bip sum')
sum1 = df6['Bip'].sum()
print('Total Bip: ' + str(sum1))
print('')
print('---------------------------------------')
print('Calculate the average people of all countries')
sum2 = df['People'].sum()/row_count
print('Avrg People: ' + str(round(sum2)))
print('')
print('---------------------------------------')
print('Sort by name alphabetically')
df7 = df.sort_values(by=['Name'])
print(df7)
print('')
print('---------------------------------------')
print('Create a new data frame from the original where the area is changed as follows: all countries with > 1000000 get BIG and <= 1000000 get SMALL in the cell replaced')
df8 = df
df8['Area'] = np.where(df8['Area'] > 1000000, 'BIG', 'SMALL')
print(df8)


Basic informations
Number of rows  5
Number of columns  5

---------------------------------------
Show the last 4 rows of the data frame.
       Name     People     Area   BIP Currency
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL

---------------------------------------
Show all the row of countries who have the EURO.
      Name    People    Area   BIP Currency
0  Germany  82521653  357385  3466      EUR
3    Italy  60501718  301338  1850      EUR

---------------------------------------
Show only name and Currency in a new data frame.
       Name Currency
0   Germany      EUR
1     Japan      YEN
2    Canada      CAD
3     Italy      EUR
4  Brazilia     REAL

---------------------------------------
Show only the rows/countries that have more than 2000 BIP (it is in Milliarden USD Bruttoinlandsprodukt)
      Name     People    Area   BIP Curren